#!/bin/bash
# scripts by adi1090x

## Get data
STATUS="$(mpc status)"
Control="MPD"
[ -n "$(pgrep spotify)" ] && Control="spotify"
Cover="/tmp/.music_cover.png"
MUSIC_DIR="$HOME/Music"

## Get status
get_status() {
  icon=""
  [ $(playerctl --player=$Control status) = "Playing" ] && icon=""
  [ $(playerctl --player=$Control status) = "Paused" ] && icon=""
  echo "$icon"
}

## Get song
get_song() {
  song=$(playerctl --player=$Control metadata --format {{title}})
  [ -z "$title" ] && title="Nothing Playing"
  echo "$song"
}

## Get artist
get_artist() {
  artist=$(playerctl --player=$Control metadata --format {{artist}})
  [ -z "$artist" ] && artist="Offline"
  echo "$artist"
}

## Get time
get_time() {
  total_length=$(echo $(playerctl --player=$Control metadata | grep mpris:length |  awk '{print($3)}')/1000000 | bc)
  curr_positon=$(playerctl --player=$Control position)  
  # echo $(echo $(( $curr_positon/$total_length*100 )) | bc)
  echo $curr_positon*100/$total_length | bc 
  # echo $total_length 
}
get_ctime() {
	ctime=`mpc status | grep "#" | awk '{print $3}' | sed 's|/.*||g'`
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}
get_ttime() {
	ttime=`mpc -f %time% current`
	if [[ -z "$ttime" ]]; then
		echo "0:00"
	else
		echo "$ttime"
	fi	
}

## Get cover
get_cover() {
  albumart="$(playerctl --player=$Control metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
  [ $(playerctl --player=$Control metadata mpris:artUrl) ] && curl -s "$albumart" --output $Cover || cp $bkpCover $Cover 
  echo "$Cover"
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--time" ]]; then
	get_time
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--ttime" ]]; then
	get_ttime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	mpc -q toggle
elif [[ "$1" == "--next" ]]; then
	{ mpc -q next; get_cover; }
elif [[ "$1" == "--prev" ]]; then
	{ mpc -q prev; get_cover; }
fi
