#!/bin/sh
workspaces() {

ws1="1"
ws2="2"
ws3="3"
ws4="4"
ws5="5"
ws6="6"
ws8="8"
ws9="9"
ws0="0"

# Unoccupied
un="0"

# check if Occupied
o1=$(swaymsg -p -t get_workspaces | grep "Workspace 1"| awk '{print($2)}')
o2=$(swaymsg -p -t get_workspaces | grep "Workspace 2"| awk '{print($2)}')
o3=$(swaymsg -p -t get_workspaces | grep "Workspace 3"| awk '{print($2)}')
o4=$(swaymsg -p -t get_workspaces | grep "Workspace 4"| awk '{print($2)}')
o5=$(swaymsg -p -t get_workspaces | grep "Workspace 5"| awk '{print($2)}')
o6=$(swaymsg -p -t get_workspaces | grep "Workspace 6"| awk '{print($2)}')
o7=$(swaymsg -p -t get_workspaces | grep "Workspace 7"| awk '{print($2)}')
o8=$(swaymsg -p -t get_workspaces | grep "Workspace 8"| awk '{print($2)}')
o9=$(swaymsg -p -t get_workspaces | grep "Workspace 9"| awk '{print($2)}')
o0=$(swaymsg -p -t get_workspaces | grep "Workspace 0"| awk '{print($2)}')

# check if Focused
f1=$(swaymsg -p -t get_workspaces | grep "Workspace 1" | grep "focused"| awk '{print($2)}')
f2=$(swaymsg -p -t get_workspaces | grep "Workspace 2" | grep "focused"| awk '{print($2)}')
f3=$(swaymsg -p -t get_workspaces | grep "Workspace 3" | grep "focused"| awk '{print($2)}')
f4=$(swaymsg -p -t get_workspaces | grep "Workspace 4" | grep "focused"| awk '{print($2)}')
f5=$(swaymsg -p -t get_workspaces | grep "Workspace 5" | grep "focused"| awk '{print($2)}')
f6=$(swaymsg -p -t get_workspaces | grep "Workspace 6" | grep "focused"| awk '{print($2)}')
f7=$(swaymsg -p -t get_workspaces | grep "Workspace 7" | grep "focused"| awk '{print($2)}')
f8=$(swaymsg -p -t get_workspaces | grep "Workspace 8" | grep "focused"| awk '{print($2)}')
f9=$(swaymsg -p -t get_workspaces | grep "Workspace 9" | grep "focused"| awk '{print($2)}')
f0=$(swaymsg -p -t get_workspaces | grep "Workspace 0" | grep "focused"| awk '{print($2)}')

ic_1=""
ic_2=""
ic_3=""
ic_4=""
ic_5=""
ic_6=""
ic_7=""
ic_8=""
ic_9=""
ic_0=""

if [ $f1 ]; then
    ic_1=""
elif [ $f2 ]; then
    ic_2=""
elif [ $f3 ]; then
    ic_3=""
elif [ $f4 ]; then
    ic_4=""
elif [ $f5 ]; then
    ic_5=""
elif [ $f6 ]; then
    ic_6=""
elif [ $f7 ]; then
    ic_7=""
elif [ $f8 ]; then
    ic_8=""
elif [ $f9 ]; then
    ic_9=""
elif [ $f0 ]; then
    ic_0=""
fi
echo 	"(box	:class \"works\"	:orientation \"h\" :spacing 10 :space-evenly \"false\" (button :onclick \"sway workspace number $ws1\"	:class \"$un$o1$f1\" \"$ic_1\") (button :onclick \"sway workspace number $ws2\"	:class \"$un$o2$f2\" \"$ic_2\") (button :onclick \"sway workspace number $ws3\"	:class \"$un$o3$f3\" \"$ic_3\") (button :onclick \"sway workspace number $ws4\"	:class \"$un$o4$f4\" \"$ic_4\") (button :onclick \"sway workspace number $ws5\"	:class \"$un$o5$f5\" \"$ic_5\") (button :onclick \"sway workspace number $ws6\"	:class \"$un$o6$f6\" \"$ic_6\") (button :onclick \"sway workspace number $ws7\"	:class \"$un$o7$f7\" \"$ic_7\") (button :onclick \"sway workspace number $ws8\"	:class \"$un$o8$f8\" \"$ic_8\") (button :onclick \"sway workspace number $ws9\"	:class \"$un$o9$f9\" \"$ic_9\") )"

}
workspaces
swaymsg -t subscribe -m '["workspace"]'| while read -r _ ; do
workspaces
done
